version: '3'

services:
  queue:
    build: .
    command: python3 main.py
    restart: always
    environment:
      API_ENV: ${API_ENV}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis1:
    image: redis
    container_name: redis_queue
    restart: no
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    restart: no
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    ports:
      - 3000:3000