version: '3'

services:
  queue:
    build: .
    command:
      - python3 main.py
    environment:
      API_ENV: ${API_ENV}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}

  redis1:
    image: redis:alpine
    container_name: redis_queue
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command:
      - redis-server /usr/local/conf/redis.conf

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: always
    ports:
      - 3000:3000