name: B2C Deeplol Riot Api Queue

on:
  push:
    branches:
      - main

jobs:
  cd_part:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo git pull
            sudo docker-compose build
            sudo docker-compose down
            sudo docker-compose up -d