name: B2C Deeplol Riot Api Queue

on:
  push:
    branches:
      - main

jobs:
  cd_part:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-00f3afd6aadf0c5ca --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd ~/B2C_Deeplol_Riot_Api_Queue
            echo "API_ENV=prod" > ./.env
            echo "AWS_ACCESS=${{ secrets.AWS_ACCESS }}" >> ./.env
            echo "AWS_SECRET=${{ secrets.AWS_SECRET }}" >> ./.env
            
            sudo git pull
            sudo docker-compose build
            sudo docker-compose down
            sudo docker-compose up -d